// <auto-generated />
using ChatBotDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatBotDb.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20260302133444_AddBouquetPrices")]
    partial class AddBouquetPrices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ChatBotDb.BouquetPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfFlowers")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BouquetPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "3 flowers arranged with a little bit of green grass",
                            NumberOfFlowers = 3,
                            Price = 15m,
                            Size = "Small"
                        },
                        new
                        {
                            Id = 2,
                            Description = "5 flowers nicely arranged, including some larger green leaves as decoration",
                            NumberOfFlowers = 5,
                            Price = 25m,
                            Size = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Description = "10 flowers, beautifully arranged with greenery and smaller filler flowers",
                            NumberOfFlowers = 10,
                            Price = 35m,
                            Size = "Large"
                        });
                });

            modelBuilder.Entity("ChatBotDb.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionData")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("ChatBotDb.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Flower")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
